package com.bluntsoftware.app.modules.user_manager.repository;

import com.bluntsoftware.app.modules.user_manager.domain.ApplicationPersistentToken;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: ApplicationPersistentToken.
* @author autogenerated
*/

@Repository("user_managerApplicationPersistentTokenRepository")
@Qualifier("user_manager")
//@RepositoryRestResource(collectionResourceRel="user_manager.ApplicationPersistentToken", path="user_manager/ApplicationPersistentToken")
public interface ApplicationPersistentTokenRepository extends GenericRepository<ApplicationPersistentToken,Integer>  {

}