package com.bluntsoftware.app.modules.user_manager.repository;

import com.bluntsoftware.app.modules.user_manager.domain.ApplicationAuthority;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: ApplicationAuthority.
* @author autogenerated
*/

@Repository("user_managerApplicationAuthorityRepository")
@Qualifier("user_manager")
//@RepositoryRestResource(collectionResourceRel="user_manager.ApplicationAuthority", path="user_manager/ApplicationAuthority")
public interface ApplicationAuthorityRepository extends GenericRepository<ApplicationAuthority,Integer>  {

}