package com.bluntsoftware.app.modules.user_manager.repository;

import com.bluntsoftware.app.modules.user_manager.domain.ApplicationUserAuthority;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: ApplicationUserAuthority.
* @author autogenerated
*/

@Repository("user_managerApplicationUserAuthorityRepository")
@Qualifier("user_manager")
//@RepositoryRestResource(collectionResourceRel="user_manager.ApplicationUserAuthority", path="user_manager/ApplicationUserAuthority")
public interface ApplicationUserAuthorityRepository extends GenericRepository<ApplicationUserAuthority,Integer>  {

}