package com.bluntsoftware.app.modules.martialarts.repository;

import com.bluntsoftware.app.modules.martialarts.domain.Address;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Address.
* @author autogenerated
*/

@Repository("martialartsAddressRepository")
@Qualifier("martialarts")
//@RepositoryRestResource(collectionResourceRel="martialarts.Address", path="martialarts/Address")
public interface AddressRepository extends GenericRepository<Address,Integer>  {

}