package com.bluntsoftware.app.modules.martialarts.repository;

import com.bluntsoftware.app.modules.martialarts.domain.Karateclass;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Karateclass.
* @author autogenerated
*/

@Repository("martialartsKarateclassRepository")
@Qualifier("martialarts")
//@RepositoryRestResource(collectionResourceRel="martialarts.Karateclass", path="martialarts/Karateclass")
public interface KarateclassRepository extends GenericRepository<Karateclass,Integer>  {

}