package com.bluntsoftware.app.modules.martialarts.repository;

import com.bluntsoftware.app.modules.martialarts.domain.School;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: School.
* @author autogenerated
*/

@Repository("martialartsSchoolRepository")
@Qualifier("martialarts")
//@RepositoryRestResource(collectionResourceRel="martialarts.School", path="martialarts/School")
public interface SchoolRepository extends GenericRepository<School,Integer>  {

}