package com.bluntsoftware.app.modules.martialarts.repository;

import com.bluntsoftware.app.modules.martialarts.domain.Student;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Student.
* @author autogenerated
*/

@Repository("martialartsStudentRepository")
@Qualifier("martialarts")
//@RepositoryRestResource(collectionResourceRel="martialarts.Student", path="martialarts/Student")
public interface StudentRepository extends GenericRepository<Student,Integer>  {

}