package com.bluntsoftware.app.modules.martialarts.repository;

import com.bluntsoftware.app.modules.martialarts.domain.Tuition;
import com.bluntsoftware.lib.jpa.repository.GenericRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.beans.factory.annotation.Qualifier;
/**
* Repository interface for table: Tuition.
* @author autogenerated
*/

@Repository("martialartsTuitionRepository")
@Qualifier("martialarts")
//@RepositoryRestResource(collectionResourceRel="martialarts.Tuition", path="martialarts/Tuition")
public interface TuitionRepository extends GenericRepository<Tuition,Integer>  {

}